language: node_js
node_js:
  - 9
cache:
  - pip
install:
  - pip install awscli --user
before_script:
  - npm install
script:
  - npm run build
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: jesse-wrong
  skip_cleanup: true
  local_dir: build
  cache_control: "max-age=21600"
after_deploy:
  # Invalidate cloudfront cache so new site is distributed
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"